In [2]:
import os
import torch
import torch.nn as nn
import numpy as np

In [3]:
input_dim = 5
hidden_dim = 10
n_layers = 1

lstm_layer = nn.LSTM(input_dim, hidden_dim, n_layers, batch_first=True) # create LSTM nn layer

In [9]:
# sizes for tensor
batch_size = 1 # batch size for data, how much data is trained at once (in one iteration)
seq_len = 1 # sequence length of the LSTM - "how many times it unrolls itself"

# generate dummy data
# size is a dynamically sized variable
inp = torch.randn(batch_size, seq_len, input_dim) # input tensor - batch_size * seq_len * input_dim size
print(inp)
hidden_state = torch.randn(n_layers, batch_size, hidden_dim) # hidden state
print(hidden_state)
cell_state = torch.randn(n_layers, batch_size, hidden_dim) # cell state
print(cell_state)
hidden = (hidden_state, cell_state) # hidden state + cell state stored in tuple

tensor([[[-0.8283, -0.5809,  1.0821, -0.4062, -0.3653]]])
tensor([[[-0.7743, -1.1925,  0.4964, -0.2805,  1.6647, -1.1450,  1.1651,
           1.0934, -1.3739,  0.2908]]])
tensor([[[-0.7724,  0.7309, -1.7308,  1.5870, -0.2994,  0.8916, -0.0591,
           0.6073, -0.7936, -0.1022]]])


In [12]:
out, hidden = lstm_layer(inp, hidden)
print("Output shape: ", out.shape)
print("Hidden layer: ", hidden)

Output shape:  torch.Size([1, 1, 10])
Hidden layer:  (tensor([[[-0.0143,  0.2428, -0.3954,  0.2575, -0.2470, -0.0405,  0.0171,
           0.1544, -0.1639, -0.0888]]], grad_fn=<StackBackward>), tensor([[[-0.0251,  0.4518, -0.7909,  0.5165, -0.5177, -0.0831,  0.0343,
           0.3913, -0.3279, -0.1972]]], grad_fn=<StackBackward>))


In [15]:
seq_len = 3
inp = torch.randn(batch_size, seq_len, input_dim)
out, hidden = lstm_layer(inp, hidden)
print(out.shape)

torch.Size([1, 3, 10])


In [16]:
# get last output
out = out.squeeze()[-1, :]
print(out.shape)
print(out)

torch.Size([10])
tensor([ 0.2422,  0.0633, -0.0863,  0.0454, -0.0050, -0.0235,  0.0989,  0.3786,
        -0.1616, -0.0126], grad_fn=<SliceBackward>)
